version: '3.9'

services:

  # Base de données
  postgres:
    image: postgres:16-alpine
    container_name: auth_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: jwt_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d jwt_auth"]
      interval: 10s
      timeout: 5s
      retries: 5

  #Application Spring Boot
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_service
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      SERVER_PORT: 8090
      DB_NAME: jwt_auth
      DB_USERNAME: postgres
      DB_PASSWORD: mysecretpassword
      JWT_SECRET_KEY: 514a42852d433eed74958366eee00216fb3c73d8528387322377c44b1095b7e0
      JWT_EXPIRATION: 86400000
      # JVM
      JAVA_OPTS: "-Xmx512m -Xms256m"
    depends_on:
      postgres:
        # Attendre que PostgreSQL soit vraiment prêt avant de démarrer l'app
        condition: service_healthy

volumes:
  postgres_data:
    name: auth_postgres_data